routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /membership/: members/membership

  /archive/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    limit: all
    template: godo-archive
    
  /:
    template: godo-home-personal
    data: page.homepage

collections:
  # Thoughts (blog)
  /thoughts/:
    permalink: /thoughts/{slug}/
    limit: 12
    template: index
    data: page.thoughts

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
